Repository wwcodeseoul/awesome-women-in-tech, pull requests merged in 2018-06, with the labels that each got.

#4 Update korean_women.md
  korean_women.md
Labels: awesome-woman

#5 이나라 프로필 추가
  korean_women.md
Labels: awesome-woman

#8 정다해 프로필 추가
  korean_women.md
Labels: awesome-woman

#10 프로필 추가요청
  korean_women.md
Labels: awesome-woman

#12 기여방법 안내 / 이벤트 추가
  contribution_guide.md
  events.md
  icons/contribution_screenshot_1.png
  icons/contribution_screenshot_2.png
  icons/contribution_screenshot_3.png
  icons/contribution_screenshot_4.png
  icons/contribution_screenshot_5.png
Labels: docs

#14 스페이스 살림 추가
  organization.md
Labels: organization

#13 REAMDE 링크 추가 / 깨진 링크 수정
  README.md
  contribution_guide.md
Labels: docs

#15 신하영 추가
  korean_women.md
Labels: awesome-woman
